### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by lolpie244** [kiyoon/jupynium.nvim#108]
**Describe the bug**
Can't run jupynium server. Get error:
```
jupynium.cmds.jupynium:   93 - INFO - Using firefox profile: None
jupynium.cmds.jupynium:  595 - ERROR - Exception occurred
Traceback (most recent call last):
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line 498, in main
    with webdriver_firefox(
         ^^^^^^^^^^^^^^^^^^
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line 102, in webdriver_firefox
    return webdriver.Firefox(options=options, service=service)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/mnt/1/Documents/labs/4.2/neural_network/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:35837
```

**To Reproduce**
`> jupynium`

**Expected behavior**
Server runs without exception

**Output of `jupynium --version`**
```
Jupynium v0.2.3.dev1+g71c3c15
```

**Output of `nvim --version`**

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**
Jupynium runs from venv

**Comment by lolpie244** [comment]
fix: https://github.com/SeleniumHQ/selenium/issues/11264#issuecomment-1315549233
